services:
  via-api:
    container_name: via-api

    build:
      context: .

    ports:
      - 8000:8000

    env_file:
      - .env

    depends_on:
      - via-mongodb

  via-mongodb:
    container_name: via-mongodb

    image: mongo:latest

    env_file:
      - .env

    ports:
      - 27017:27017
